name: kptcli
base: core22
version: 'v1.0.0-beta.39'
summary: Automate Kubernetes Configuration Editing
license: Apache-2.0
contact: guillaume.belanger@canonical.com
issues: https://github.com/gruyaume/kptcli/issues
source-code: https://github.com/gruyaume/kptcli
description: |
  kpt is a package-centric toolchain that enables a WYSIWYG configuration authoring, automation, 
  and delivery experience, which simplifies managing Kubernetes platforms and KRM-driven 
  infrastructure (e.g., Config Connector, Crossplane) at scale by manipulating declarative 
  Configuration as Data.
grade: stable
confinement: strict

apps:
  kpt:
    command: bin/kpt
    environment:
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_CONFIG_NOSYSTEM: 1

parts:
  kpt:
    plugin: go
    build-snaps:
      - go/1.20/stable
    stage-packages:
      - git
    source: https://github.com/GoogleContainerTools/kpt.git
    source-type: git
    source-tag: v1.0.0-beta.39
